### PR TITLE
This fixes issues with Django 1.5. django.http.get_host()

### PR DESCRIPTION
**Pull request by fmyzjs**
This fixes issues with Django 1.5. django.http.get_host() was replaced with request.get_host()

### CODE REVIEW

**Comment by carsongee** [comment]
The platform is pinned to Django 1.4, so there isn't a current need to change these. That said, do these changes work with Django 1.4 as well?

**Comment by fmyzjs** [comment]
Sure,edustack fork work very well

**Comment by carsongee** [comment]
I verified that this is good to go. I will merge as soon as we merge https://github.com/edx/edx-platform/pull/6127

**Comment by pdpinch** [comment]
@carsongee can/should this be merged now?

**Comment by carsongee** [comment]
I guess so

**Pull request merged**
